spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsinjo_preprod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

vola:
  api:
    key: ${VOLA_API_KEY}
    url: https://42cwka3n4ifcp7ufheyrpmph240iuaxo.lambda-url.eu-west-3.on.aws

logging:
  level:
    com.company.school.tsinjo: DEBUG
